### ISSUE TITLE
Debug mode crashes in ree

### ISSUE THREAD

**Issue by josephruscio** [josephruscio/rack-test-rest#8]
Example:

```
NoMethodError: undefined method `pretty_inspect' for {}:Hash
    /Users/jruscio/.rvm/gems/ree-1.8.7-2011.03@librato/gems/rack-test-rest-0.4.3/lib/rack-test-rest.rb:63:in `read_resource'
    test/../test/../test/../test/../test/../test/../test/../test/../test/../test/../test/../test/../test/annotation_test.rb:39:in `test_get_annotation'
```

**Comment by nextmat** [comment]
Fixed by b10339677b8bc512647c5b8db6e86f3cb0d41ca2, should now work with 1.8.6 and up.

_edit_ fixed originally wrong commit hash
